POST http://localhost:8080/submitApplication
Content-Type: application/json

{
  "firstName": "Joe",
  "lastName": "Bloggs",
  "email": "joe@bloggs.com",
  "amount": 100,
  "claimType": "FLOODS",
  "bankAccountName": "Joe Bloggs",
  "bankAccountNumber": "10876543",
  "bsb": "067432"
}

###