apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
data:
  username: SUtSUVhBSVNVWTdOMjIzQg==
  password: T2JPL3VwOE5iNDJDbnI1S3FXMmdrV05YWm4yVE9hZ25EQUQ5QzFUYU5IUzkrbk1PK2R6QzAvZVR2R3locjAzNQ==
  broker: cGtjLWxkdmoxLmFwLXNvdXRoZWFzdC0yLmF3cy5jb25mbHVlbnQuY2xvdWQ=