apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-app-deployment
  name: my-claim-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: my-app-deployment
status:
  loadBalancer: {}