package example.claims.eventdriven.models;

public enum ApplicationState {
   APPLICATION_STATE_NEW, APPLICATION_STATE_ELIGIBILITY_CHECK_SUCCESS, APPLICATION_STATE_ELIGIBILITY_CHECK_FAIL,
   APPLICATION_STATE_FRAUD_CHECK_FAIL,  APPLICATION_STATE_FRAUD_CHECK_SUCCESS, APPLICATION_STATE_PAYMENT_INITIATED,
   APPLICATION_STATE_PAYMENT_REJECTED, APPLICATION_STATE_PAYMENT_SUCCESSFUL
}
