spring:
  data:
    mongodb:
      host: localhost
      database: mydatabase
      password: secret
      username: root
      uri: mongodb://root:secret@localhost:27017/mydatabase?authSource=admin&authMechanism=SCRAM-SHA-1
server:
  port: 8081
